spring:
  h2:
    console:
      path: /console

security:
  user:
    name: user
    password: password
    role: USER

liquibase:
      change-log: classpath:/liquibase/changelogs/db.changelog-master.xml