spring:
  h2:
    console:
      path: /console
  liquibase:
    change-log: classpath:/liquibase/changelogs/db.changelog-master.xml

security:
  user:
    name: user
    password: password
    role: USER

