---
swagger: "2.0"
info:
  description: "This is a sample spec for our REST API"
  version: "v1"
  title: "Swagger spec for our REST API"
  termsOfService: "http://www.testcompany.com/terms-and-conditions"
  contact:
    name: "Suresh Satyam"
    url: "http://www.testcompany.com"
    email: "SureshSatyam(@)testcompany.com"
  license:
    name: "Company Licence"
    url: "http://www.testcompany.com/licenses/LICENSE-2.0.html"
host: "www.[host]:[port]"
basePath: "/v1"
tags:
- name: "studnets"
schemes:
- "http"
- "https"
paths:
  /students/{id}:
    get:
      tags:
      - "studnets"
      summary: "Returns Student details"
      description: "Returns Student details."
      operationId: "getStudent"
      parameters:
      - name: ""
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Result"
          schema:
            $ref: "#/definitions/Student"
definitions:
  Guide:
    type: "object"
    properties:
      name:
        type: "string"
  Student:
    type: "object"
    properties:
      name:
        type: "string"
      guide:
        $ref: "#/definitions/Guide"
